//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';


export interface IConsultaMenorClient {
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestrosConsultaMenor(x_api_version?: string | undefined, body?: ObtenerMaestrosConsultaMenorRequest | undefined, signal?: AbortSignal): Promise<ObtenerMaestrosConsultaMenorResponse>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerExpedientesDelMenor(x_api_version?: string | undefined, body?: ObtenerExpedientesDelMenorQuery | undefined, signal?: AbortSignal): Promise<ObtenerExpedientesDelMenorResponse>;
}

export class ConsultaMenorClient implements IConsultaMenorClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestrosConsultaMenor(x_api_version?: string | undefined, body?: ObtenerMaestrosConsultaMenorRequest | undefined, signal?: AbortSignal): Promise<ObtenerMaestrosConsultaMenorResponse> {
        let url_ = this.baseUrl + "/api/v1/ConsultaMenor/ObtenerMaestrosConsultaMenor";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processObtenerMaestrosConsultaMenor(_response);
        });
    }

    protected processObtenerMaestrosConsultaMenor(response: AxiosResponse): Promise<ObtenerMaestrosConsultaMenorResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200;
            return Promise.resolve<ObtenerMaestrosConsultaMenorResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ObtenerMaestrosConsultaMenorResponse>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerExpedientesDelMenor(x_api_version?: string | undefined, body?: ObtenerExpedientesDelMenorQuery | undefined, signal?: AbortSignal): Promise<ObtenerExpedientesDelMenorResponse> {
        let url_ = this.baseUrl + "/api/v1/ConsultaMenor/ObtenerExpedientesDelMenor";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processObtenerExpedientesDelMenor(_response);
        });
    }

    protected processObtenerExpedientesDelMenor(response: AxiosResponse): Promise<ObtenerExpedientesDelMenorResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = resultData200;
            return Promise.resolve<ObtenerExpedientesDelMenorResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ObtenerExpedientesDelMenorResponse>(null as any);
    }
}

export interface ExpedienteResponse {
    refExpediente: string | undefined;
    organo: string | undefined;
    fechaIncoacion?: Date | undefined;
    estado: string | undefined;
    fiscal: string | undefined;
    fechaArchivo?: Date | undefined;
    observaciones?: string | undefined;
}

export interface ObtenerExpedientesDelMenorQuery {
    nombre?: string | undefined;
    primerApellido?: string | undefined;
    segundoApellido?: string | undefined;
    fechaNacimiento?: Date | undefined;
    codigoPais?: string | undefined;
    codigoTipoIdentificacion?: string | undefined;
    numeroIdentificacion?: string | undefined;
}

export interface ObtenerExpedientesDelMenorResponse {
    expedientes: ExpedienteResponse[] | undefined;
}

export interface ObtenerMaestrosConsultaMenorRequest {
}

export interface ObtenerMaestrosConsultaMenorResponse {
    paises?: Pais[] | undefined;
    tiposIdentificacion?: TipoIdentificacion[] | undefined;
}

export interface Pais {
    idPais?: number;
    codigoCTEAJE?: string | undefined;
    descripcion?: string | undefined;
}

export interface TipoIdentificacion {
    idTipoIdentificacion?: number;
    codigo?: string | undefined;
    descripcion?: string | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}