//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

import dayjs from 'dayjs';

export interface IBuscadorOperacionesClient {
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestrosBaseBuscadorOperaciones(x_api_version?: string | undefined, body?: ObtenerMaestrosBaseBuscadorOperacionesQuery | undefined): Promise<ObtenerMaestrosBaseBuscadorOperacionesResponse>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerListadoOperaciones(x_api_version?: string | undefined, body?: BuscarOperacionesPorEstadoCommand | undefined): Promise<ListadoOperacionesVM>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    confirmarOperacion(x_api_version?: string | undefined, body?: ConfirmacionOperacionCECommand | undefined): Promise<ConfirmacionOperacionCEResponseVM>;
}

export class BuscadorOperacionesClient implements IBuscadorOperacionesClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestrosBaseBuscadorOperaciones(x_api_version?: string | undefined, body?: ObtenerMaestrosBaseBuscadorOperacionesQuery | undefined, signal?: AbortSignal): Promise<ObtenerMaestrosBaseBuscadorOperacionesResponse> {
        let url_ = this.baseUrl + "/api/BuscadorOperaciones/ObtenerMaestrosBaseBuscadorOperaciones";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processObtenerMaestrosBaseBuscadorOperaciones(_response);
        });
    }

    protected processObtenerMaestrosBaseBuscadorOperaciones(response: AxiosResponse): Promise<ObtenerMaestrosBaseBuscadorOperacionesResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ObtenerMaestrosBaseBuscadorOperacionesResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ObtenerMaestrosBaseBuscadorOperacionesResponse>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerListadoOperaciones(x_api_version?: string | undefined, body?: BuscarOperacionesPorEstadoCommand | undefined, signal?: AbortSignal): Promise<ListadoOperacionesVM> {
        let url_ = this.baseUrl + "/api/BuscadorOperaciones/ObtenerListadoOperaciones";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processObtenerListadoOperaciones(_response);
        });
    }

    protected processObtenerListadoOperaciones(response: AxiosResponse): Promise<ListadoOperacionesVM> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ListadoOperacionesVM>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ListadoOperacionesVM>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    confirmarOperacion(x_api_version?: string | undefined, body?: ConfirmacionOperacionCECommand | undefined, signal?: AbortSignal): Promise<ConfirmacionOperacionCEResponseVM> {
        let url_ = this.baseUrl + "/api/BuscadorOperaciones/ConfirmarOperacion";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processConfirmarOperacion(_response);
        });
    }

    protected processConfirmarOperacion(response: AxiosResponse): Promise<ConfirmacionOperacionCEResponseVM> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ConfirmacionOperacionCEResponseVM>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ConfirmacionOperacionCEResponseVM>(null as any);
    }
}

export interface IErroresCDCJClient {
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestros(x_api_version?: string | undefined, body?: ObtenerMaestrosBuscadorErroresCDCJQuery | undefined): Promise<ObtenerMaestrosBuscadorErroresCDCJResponse>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    buscarErrores(x_api_version?: string | undefined, body?: BuscarErroresCDCJQuery | undefined): Promise<BuscarErroresCDCJResponseVM>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    marcarVisto(x_api_version?: string | undefined, body?: MarcarErrorVistoCommand | undefined): Promise<void>;
}

export class ErroresCDCJClient implements IErroresCDCJClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestros(x_api_version?: string | undefined, body?: ObtenerMaestrosBuscadorErroresCDCJQuery | undefined, signal?: AbortSignal): Promise<ObtenerMaestrosBuscadorErroresCDCJResponse> {
        let url_ = this.baseUrl + "/api/ErroresCDCJ/ObtenerMaestros";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processObtenerMaestros(_response);
        });
    }

    protected processObtenerMaestros(response: AxiosResponse): Promise<ObtenerMaestrosBuscadorErroresCDCJResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ObtenerMaestrosBuscadorErroresCDCJResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ObtenerMaestrosBuscadorErroresCDCJResponse>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    buscarErrores(x_api_version?: string | undefined, body?: BuscarErroresCDCJQuery | undefined, signal?: AbortSignal): Promise<BuscarErroresCDCJResponseVM> {
        let url_ = this.baseUrl + "/api/ErroresCDCJ/BuscarErrores";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processBuscarErrores(_response);
        });
    }

    protected processBuscarErrores(response: AxiosResponse): Promise<BuscarErroresCDCJResponseVM> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<BuscarErroresCDCJResponseVM>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<BuscarErroresCDCJResponseVM>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    marcarVisto(x_api_version?: string | undefined, body?: MarcarErrorVistoCommand | undefined, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/ErroresCDCJ/MarcarVisto";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processMarcarVisto(_response);
        });
    }

    protected processMarcarVisto(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }
}

export interface IOperacionesClient {
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    altaCE(x_api_version?: string | undefined, body?: AltaCECommand | undefined): Promise<AltaCEResponseVM>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    detalleCE(x_api_version?: string | undefined, body?: DetalleCECommand | undefined): Promise<DetalleCEResponseVM>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    transferenciaCE(x_api_version?: string | undefined, body?: TransferenciaCECommand | undefined): Promise<TransferenciaCEResponseVM>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    traspasoCE(x_api_version?: string | undefined, body?: TraspasoCECommand | undefined): Promise<TraspasoCEResponseVM>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    altaMandamientoPagoCE(x_api_version?: string | undefined, body?: AltaMandamientoPagoCECommand | undefined): Promise<AltaMandamientoPagoVM>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    accesoProfesionalesCE(x_api_version?: string | undefined, body?: AccesoProfesionalesCECommand | undefined): Promise<AccesoProfesionalesCEResponseVM[]>;
}

export class OperacionesClient implements IOperacionesClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    altaCE(x_api_version?: string | undefined, body?: AltaCECommand | undefined, signal?: AbortSignal): Promise<AltaCEResponseVM> {
        let url_ = this.baseUrl + "/api/Operaciones/AltaCE";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAltaCE(_response);
        });
    }

    protected processAltaCE(response: AxiosResponse): Promise<AltaCEResponseVM> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<AltaCEResponseVM>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<AltaCEResponseVM>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    detalleCE(x_api_version?: string | undefined, body?: DetalleCECommand | undefined, signal?: AbortSignal): Promise<DetalleCEResponseVM> {
        let url_ = this.baseUrl + "/api/Operaciones/DetalleCE";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDetalleCE(_response);
        });
    }

    protected processDetalleCE(response: AxiosResponse): Promise<DetalleCEResponseVM> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<DetalleCEResponseVM>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<DetalleCEResponseVM>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    transferenciaCE(x_api_version?: string | undefined, body?: TransferenciaCECommand | undefined, signal?: AbortSignal): Promise<TransferenciaCEResponseVM> {
        let url_ = this.baseUrl + "/api/Operaciones/TransferenciaCE";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processTransferenciaCE(_response);
        });
    }

    protected processTransferenciaCE(response: AxiosResponse): Promise<TransferenciaCEResponseVM> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<TransferenciaCEResponseVM>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<TransferenciaCEResponseVM>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    traspasoCE(x_api_version?: string | undefined, body?: TraspasoCECommand | undefined, signal?: AbortSignal): Promise<TraspasoCEResponseVM> {
        let url_ = this.baseUrl + "/api/Operaciones/TraspasoCE";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processTraspasoCE(_response);
        });
    }

    protected processTraspasoCE(response: AxiosResponse): Promise<TraspasoCEResponseVM> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<TraspasoCEResponseVM>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<TraspasoCEResponseVM>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    altaMandamientoPagoCE(x_api_version?: string | undefined, body?: AltaMandamientoPagoCECommand | undefined, signal?: AbortSignal): Promise<AltaMandamientoPagoVM> {
        let url_ = this.baseUrl + "/api/Operaciones/AltaMandamientoPagoCE";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAltaMandamientoPagoCE(_response);
        });
    }

    protected processAltaMandamientoPagoCE(response: AxiosResponse): Promise<AltaMandamientoPagoVM> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<AltaMandamientoPagoVM>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<AltaMandamientoPagoVM>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    accesoProfesionalesCE(x_api_version?: string | undefined, body?: AccesoProfesionalesCECommand | undefined, signal?: AbortSignal): Promise<AccesoProfesionalesCEResponseVM[]> {
        let url_ = this.baseUrl + "/api/Operaciones/AccesoProfesionalesCE";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAccesoProfesionalesCE(_response);
        });
    }

    protected processAccesoProfesionalesCE(response: AxiosResponse): Promise<AccesoProfesionalesCEResponseVM[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<AccesoProfesionalesCEResponseVM[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<AccesoProfesionalesCEResponseVM[]>(null as any);
    }
}

export interface IRegistroOperacionClient {
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestrosBaseRegistroOperacion(x_api_version?: string | undefined, body?: ObtenerMaestrosBaseOperacionesCDCJQuery | undefined): Promise<ObtenerMaestrosOperacionesCDCJResponse>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestrosTransferencia(x_api_version?: string | undefined, body?: ObtenerMaestrosTransferenciaQuery | undefined): Promise<ObtenerMaestrosTransferenciaResponse>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestrosTraspaso(x_api_version?: string | undefined, body?: ObtenerMaestrosTraspasoQuery | undefined): Promise<ObtenerMaestrosTraspasoResponse>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestrosMandamientoPago(x_api_version?: string | undefined, body?: ObtenerMaestrosMandamientoPagoQuery | undefined): Promise<ObtenerMaestrosMandamientoPagoResponse>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerDatosDestinoPorExpediente(x_api_version?: string | undefined, body?: ObtenerDatosPorExpedienteQuery | undefined): Promise<DatosExpedienteOrganoDTO>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMunicipiosPorProvincia(x_api_version?: string | undefined, body?: ObtenerMunicipiosPorProvinciaQuery | undefined): Promise<void>;
}

export class RegistroOperacionClient implements IRegistroOperacionClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestrosBaseRegistroOperacion(x_api_version?: string | undefined, body?: ObtenerMaestrosBaseOperacionesCDCJQuery | undefined, signal?: AbortSignal): Promise<ObtenerMaestrosOperacionesCDCJResponse> {
        let url_ = this.baseUrl + "/api/RegistroOperacion/ObtenerMaestrosBaseRegistroOperacion";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processObtenerMaestrosBaseRegistroOperacion(_response);
        });
    }

    protected processObtenerMaestrosBaseRegistroOperacion(response: AxiosResponse): Promise<ObtenerMaestrosOperacionesCDCJResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ObtenerMaestrosOperacionesCDCJResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ObtenerMaestrosOperacionesCDCJResponse>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestrosTransferencia(x_api_version?: string | undefined, body?: ObtenerMaestrosTransferenciaQuery | undefined, signal?: AbortSignal): Promise<ObtenerMaestrosTransferenciaResponse> {
        let url_ = this.baseUrl + "/api/RegistroOperacion/ObtenerMaestrosTransferencia";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processObtenerMaestrosTransferencia(_response);
        });
    }

    protected processObtenerMaestrosTransferencia(response: AxiosResponse): Promise<ObtenerMaestrosTransferenciaResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ObtenerMaestrosTransferenciaResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ObtenerMaestrosTransferenciaResponse>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestrosTraspaso(x_api_version?: string | undefined, body?: ObtenerMaestrosTraspasoQuery | undefined, signal?: AbortSignal): Promise<ObtenerMaestrosTraspasoResponse> {
        let url_ = this.baseUrl + "/api/RegistroOperacion/ObtenerMaestrosTraspaso";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processObtenerMaestrosTraspaso(_response);
        });
    }

    protected processObtenerMaestrosTraspaso(response: AxiosResponse): Promise<ObtenerMaestrosTraspasoResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ObtenerMaestrosTraspasoResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ObtenerMaestrosTraspasoResponse>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMaestrosMandamientoPago(x_api_version?: string | undefined, body?: ObtenerMaestrosMandamientoPagoQuery | undefined, signal?: AbortSignal): Promise<ObtenerMaestrosMandamientoPagoResponse> {
        let url_ = this.baseUrl + "/api/RegistroOperacion/ObtenerMaestrosMandamientoPago";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processObtenerMaestrosMandamientoPago(_response);
        });
    }

    protected processObtenerMaestrosMandamientoPago(response: AxiosResponse): Promise<ObtenerMaestrosMandamientoPagoResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ObtenerMaestrosMandamientoPagoResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ObtenerMaestrosMandamientoPagoResponse>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerDatosDestinoPorExpediente(x_api_version?: string | undefined, body?: ObtenerDatosPorExpedienteQuery | undefined, signal?: AbortSignal): Promise<DatosExpedienteOrganoDTO> {
        let url_ = this.baseUrl + "/api/RegistroOperacion/ObtenerDatosDestinoPorExpediente";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processObtenerDatosDestinoPorExpediente(_response);
        });
    }

    protected processObtenerDatosDestinoPorExpediente(response: AxiosResponse): Promise<DatosExpedienteOrganoDTO> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<DatosExpedienteOrganoDTO>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<DatosExpedienteOrganoDTO>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    obtenerMunicipiosPorProvincia(x_api_version?: string | undefined, body?: ObtenerMunicipiosPorProvinciaQuery | undefined, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/RegistroOperacion/ObtenerMunicipiosPorProvincia";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processObtenerMunicipiosPorProvincia(_response);
        });
    }

    protected processObtenerMunicipiosPorProvincia(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }
}

export interface IRelacionesClient {
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    consultarRelacionPorExpediente(x_api_version?: string | undefined, body?: ConsultarRelacionPorExpedienteQuery | undefined): Promise<ConsultaRelacionVM>;
    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    relacionarCuentaExpediente(x_api_version?: string | undefined, body?: RelacionarCuentaExpedienteCommand | undefined): Promise<RelacionarCuentaExpedienteVM>;
}

export class RelacionesClient implements IRelacionesClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    consultarRelacionPorExpediente(x_api_version?: string | undefined, body?: ConsultarRelacionPorExpedienteQuery | undefined, signal?: AbortSignal): Promise<ConsultaRelacionVM> {
        let url_ = this.baseUrl + "/api/Relaciones/ConsultarRelacionPorExpediente";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processConsultarRelacionPorExpediente(_response);
        });
    }

    protected processConsultarRelacionPorExpediente(response: AxiosResponse): Promise<ConsultaRelacionVM> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<ConsultaRelacionVM>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<ConsultaRelacionVM>(null as any);
    }

    /**
     * @param x_api_version (optional) 
     * @param body (optional) 
     * @return OK
     */
    relacionarCuentaExpediente(x_api_version?: string | undefined, body?: RelacionarCuentaExpedienteCommand | undefined, signal?: AbortSignal): Promise<RelacionarCuentaExpedienteVM> {
        let url_ = this.baseUrl + "/api/Relaciones/RelacionarCuentaExpediente";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "x-api-version": x_api_version !== undefined && x_api_version !== null ? "" + x_api_version : "",
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRelacionarCuentaExpediente(_response);
        });
    }

    protected processRelacionarCuentaExpediente(response: AxiosResponse): Promise<RelacionarCuentaExpedienteVM> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<RelacionarCuentaExpedienteVM>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<RelacionarCuentaExpedienteVM>(null as any);
    }
}

export interface AccesoProfesionalesCECommand {
    datosAccesoProfesionalesCE?: DatosAccesoProfesionalesCECommandDTO;
}

export interface AccesoProfesionalesCEResponseVM {
    estado?: string | undefined;
    codRespuesta?: string | undefined;
    desRespuesta?: string | undefined;
    resultadoErroneo?: boolean;
    error?: string | undefined;
}

export interface AltaCECommand {
    idExpedienteEncriptado?: string | undefined;
}

export interface AltaCEResponseVM {
    codExpediente?: string | undefined;
    codSituExp?: string | undefined;
    codRespuesta?: string | undefined;
    desRespuesta?: string | undefined;
    resultadoErroneo?: boolean;
    error?: string | undefined;
}

export interface AltaMandamientoPagoCECommand {
    datos?: DatosAltaMandamientoPagoCECommandDTO;
}

export interface AltaMandamientoPagoCE_ResponseDTO {
    num_operacion?: number;
    cod_seralfab?: string | undefined;
    num_sr?: string | undefined;
    fecha?: dayjs.Dayjs;
    fec_caduca?: dayjs.Dayjs;
    estado?: string | undefined;
    cod_respuesta?: string | undefined;
    des_respuesta?: string | undefined;
}

export interface AltaMandamientoPagoCE_ResponseRootDTO {
    altaMandamientoPagoResponse?: AltaMandamientoPagoCE_ResponseDTO;
}

export interface AltaMandamientoPagoVM {
    altaMandamientoPagoResponse?: AltaMandamientoPagoCE_ResponseRootDTO[] | undefined;
    resultadoErroneo?: boolean;
    error?: string | undefined;
}

export interface BuscarErroresCDCJFiltrosDTO {
    numeroProcedimiento?: string | undefined;
    anoProcedimiento?: string | undefined;
    idTipoProcedimiento?: number | undefined;
    idOperacionCDCJ?: number | undefined;
    fechaDesde?: dayjs.Dayjs | undefined;
    fechaHasta?: dayjs.Dayjs | undefined;
    soloMisExpedientes?: boolean;
    idGrupoTrabajo?: number | undefined;
}

export interface BuscarErroresCDCJQuery {
    filtros?: BuscarErroresCDCJFiltrosDTO;
}

export interface BuscarErroresCDCJResponseVM {
    items?: ErrorCDCJItemVM[] | undefined;
    masDe100Resultados?: boolean;
}

export interface BuscarOperacionesPorEstadoCommand {
    datos?: DatosOperacionesCECommandDTO;
}

export interface ConfirmacionOperacionCECommand {
    datosConfirmacion?: DatosConfirmarOperacionCECommandDTO;
}

export interface ConfirmacionOperacionCEResponseVM {
    confirmaroperacion?: ConfirmarOperacionDTO;
    resultadoErroneo?: boolean;
    error?: string | undefined;
}

export interface ConfirmarOperacionDTO {
    estadoOperacion?: string | undefined;
    codRespuesta?: string | undefined;
    desRespuesta?: string | undefined;
}

export interface ConsultaRelacionVM {
    resultadoErroneo?: boolean;
    error?: string | undefined;
    relaciones?: RelacionVM[] | undefined;
    numPagina?: number | undefined;
}

export interface ConsultarRelacionPorExpedienteQuery {
    idExpedienteEncriptado?: string | undefined;
}

export interface DatosAccesoProfesionalesCECommandDTO {
    idExpedientesEncriptados?: string[] | undefined;
    accion?: string | undefined;
    idRepresentantesAnteriores?: string[] | undefined;
    idRepresentanteNuevo?: string | undefined;
    idInterviniente?: string | undefined;
}

export interface DatosAltaMandamientoPagoCECommandDTO {
    numeroProcedimiento?: string | undefined;
    anyoProcedimiento?: string | undefined;
    pieza?: number;
    tipDocumento?: string | undefined;
    codDocumento?: string | undefined;
    nombre?: string | undefined;
    tipDocumentoMp?: string | undefined;
    codDocumentoMp?: string | undefined;
    expNoDispone?: string | undefined;
    codConcepto?: string | undefined;
    desConcepto?: string | undefined;
    importe?: number;
    codMoneda?: string | undefined;
    localizacion?: string | undefined;
    tipoPago?: string | undefined;
    codEntidad?: string | undefined;
    codOficina?: string | undefined;
    digControl?: string | undefined;
    codCcc?: string | undefined;
    codCtaiban?: string | undefined;
    ctaBenef?: string | undefined;
    codSwift?: string | undefined;
    motivoNoBancarizado?: string | undefined;
    indResid?: boolean;
    desObserv?: string | undefined;
    codTipovia?: string | undefined;
    nomVia?: string | undefined;
    numVia?: string | undefined;
    codPostal?: string | undefined;
    codPais?: string | undefined;
    codProvincia?: string | undefined;
    codPlaza?: string | undefined;
    numTelefono?: string | undefined;
    tipoNotificacion?: string | undefined;
    numSmsNotificacion?: string | undefined;
    emailNotificacion?: string | undefined;
    estado?: string | undefined;
}

export interface DatosBaseProcedimientoDTO {
    numero?: string | undefined;
    ano?: string | undefined;
    pieza?: number;
}

export interface DatosConfirmarOperacionCECommandDTO {
    unidadFuncional?: string | undefined;
    numeroOperacion?: string | undefined;
    tipDocumento?: string | undefined;
    codDocumento?: string | undefined;
}

export interface DatosDetalleCECommandDTO {
    idExpediente?: number;
    idExpedienteEncriptado?: string | undefined;
    fechaIni?: string | undefined;
    fechaFin?: string | undefined;
    importeDesde?: number | undefined;
    importeHasta?: number | undefined;
    moneda?: string | undefined;
    tipoMovimiento?: string | undefined;
    ordenacion?: string | undefined;
    numPagina?: number | undefined;
    tamPagina?: number | undefined;
}

export interface DatosExpedienteDTO {
    numeroProcedimientoConPieza?: DatosBaseProcedimientoDTO;
    tipoProcedimiento?: string | undefined;
}

export interface DatosExpedienteOrganoDTO {
    numeroProcedimientoConPieza?: DatosBaseProcedimientoDTO;
    tipoProcedimiento?: Int32MaestroClaveCodigoDTO;
    organo?: OrganoJudicialMaestroDTO;
}

export interface DatosOperacionesCECommandDTO {
    unidadFuncional?: string | undefined;
    numeroProcedimiento?: string | undefined;
    tipoProcedimiento?: string | undefined;
    subIndicePieza?: string | undefined;
    tipDocumento?: string | undefined;
    codDocumento?: string | undefined;
    fechaIni?: string | undefined;
    fechaFin?: string | undefined;
    tipoOperacion?: string | undefined;
    estado?: string | undefined;
}

export interface DatosProcedimientoDestinoTransferenciaDTO {
    idOrgano?: number;
    numeroProcedimiento?: string | undefined;
    anoProcedimiento?: string | undefined;
    pieza?: string | undefined;
    codTipoProcedimiento?: string | undefined;
}

export interface DatosProcedimientoDestinoTraspasoDTO {
    idOrgano?: number;
    numeroProcedimiento?: string | undefined;
    anoProcedimiento?: string | undefined;
    pieza?: string | undefined;
    codTipoProcedimiento?: string | undefined;
}

export interface DatosTransferenciaCECommandDTO {
    idExpedienteEncriptado?: string | undefined;
    procedimientoDestino?: DatosProcedimientoDestinoTransferenciaDTO;
    importe?: number;
    codMoneda?: string | undefined;
    codConcepto?: string | undefined;
    desConcepto?: string | undefined;
    desObserv?: string | undefined;
    nombre?: string | undefined;
    codEstado?: string | undefined;
    fecDisposicion?: dayjs.Dayjs | undefined;
}

export interface DatosTraspasoCECommandDTO {
    idExpedienteEncriptado?: string | undefined;
    procedimientoDestino?: DatosProcedimientoDestinoTraspasoDTO;
    codConcepto?: string | undefined;
    desConcepto?: string | undefined;
    desObserv?: string | undefined;
    codEstado?: string | undefined;
}

export interface DetalleCECommand {
    datosDetalleCE?: DatosDetalleCECommandDTO;
}

export interface DetalleCEResponseVM {
    resultados?: ResultadosDTO;
    totales?: TotalesDTO[] | undefined;
    numPagina?: number;
    tamPagina?: number;
    masPaginas?: boolean;
    codRespuesta?: string | undefined;
    desRespuesta?: string | undefined;
    resultadoErroneo?: boolean;
    error?: string | undefined;
}

export interface ErrorCDCJItemVM {
    idErrorCDCJ?: string;
    fechaOperacion?: dayjs.Dayjs;
    expediente?: string | undefined;
    codigoTipoProcedimiento?: string | undefined;
    descripcionOrganoJudicial?: string | undefined;
    nombreLAJ?: string | undefined;
    descripcionGrupoTrabajo?: string | undefined;
    tipoOperacion?: string | undefined;
    visto?: boolean;
    codigoError?: string | undefined;
    numeroPieza?: number | undefined;
}

export interface Importes {
    importe?: number;
}

export interface Int16MaestroClaveCodigoDescripcionVM {
    clave?: number;
    codigo?: string | undefined;
    descripcion?: string | undefined;
}

export interface Int16MaestroClaveDescripcionVM {
    clave?: number;
    descripcion?: string | undefined;
}

export interface Int32MaestroClaveDescripcionVM {
    clave?: number;
    descripcion?: string | undefined;
}

export interface Int32MaestroClaveCodigoDTO {
    clave?: number;
    descripcion?: string | undefined;
    codigo?: string | undefined;
}

export interface Int32MaestroClaveCodigoDescripcionVM {
    clave?: number;
    codigo?: string | undefined;
    descripcion?: string | undefined;
}

export interface ListadoOperacionesVM {
    operaciones?: OperacionDTO[] | undefined;
    resultadoErroneo?: boolean;
    error?: string | undefined;
}

export interface MarcarErrorVistoCommand {
    idsErrorCDCJ?: string[] | undefined;
}

export interface Monedas {
    cod_moneda?: string | undefined;
}

export interface ObtenerDatosPorExpedienteQuery {
    idExpedienteEncriptado?: string | undefined;
}

export interface ObtenerMaestrosBaseBuscadorOperacionesQuery {
}

export interface ObtenerMaestrosBaseBuscadorOperacionesResponse {
    operaciones?: Int16MaestroClaveDescripcionVM[] | undefined;
    estados?: Int16MaestroClaveDescripcionVM[] | undefined;
    tiposProcedimiento?: Int32MaestroClaveCodigoDescripcionVM[] | undefined;
}

export interface ObtenerMaestrosBaseOperacionesCDCJQuery {
    idExpedienteEncriptado?: string | undefined;
}

export interface ObtenerMaestrosBuscadorErroresCDCJQuery {
}

export interface ObtenerMaestrosBuscadorErroresCDCJResponse {
    tiposOperacion?: Int16MaestroClaveDescripcionVM[] | undefined;
    tiposProcedimiento?: Int32MaestroClaveCodigoDescripcionVM[] | undefined;
    gruposTrabajoSeccion?: Int32MaestroClaveDescripcionVM[] | undefined;
}

export interface ObtenerMaestrosMandamientoPagoQuery {
}

export interface ObtenerMaestrosMandamientoPagoResponse {
    tiposProcedimiento?: Int32MaestroClaveCodigoDescripcionVM[] | undefined;
    estadosOperacion?: Int16MaestroClaveCodigoDescripcionVM[] | undefined;
    conceptos?: Int16MaestroClaveCodigoDescripcionVM[] | undefined;
    localizaciones?: Int16MaestroClaveCodigoDescripcionVM[] | undefined;
    tipoPago?: Int16MaestroClaveCodigoDescripcionVM[] | undefined;
    tipoIdentificacion?: Int16MaestroClaveCodigoDescripcionVM[] | undefined;
    tipoVia?: Int16MaestroClaveCodigoDescripcionVM[] | undefined;
    provincias?: Int16MaestroClaveCodigoDescripcionVM[] | undefined;
    municipios?: Int32MaestroClaveCodigoDescripcionVM[] | undefined;
    monedas?: Int32MaestroClaveCodigoDescripcionVM[] | undefined;
    paises?: Int16MaestroClaveCodigoDescripcionVM[] | undefined;
}

export interface ObtenerMaestrosOperacionesCDCJResponse {
    tipoMovimientos?: Int16MaestroClaveDescripcionVM[] | undefined;
    operaciones?: Int16MaestroClaveDescripcionVM[] | undefined;
    datosExpediente?: DatosExpedienteDTO;
}

export interface ObtenerMaestrosTransferenciaQuery {
}

export interface ObtenerMaestrosTransferenciaResponse {
    tiposProcedimiento?: Int32MaestroClaveCodigoDescripcionVM[] | undefined;
    monedas?: Int32MaestroClaveCodigoDescripcionVM[] | undefined;
    estadosOperacion?: Int16MaestroClaveCodigoDescripcionVM[] | undefined;
    conceptos?: Int16MaestroClaveCodigoDescripcionVM[] | undefined;
}

export interface ObtenerMaestrosTraspasoQuery {
}

export interface ObtenerMaestrosTraspasoResponse {
    tiposProcedimiento?: Int32MaestroClaveCodigoDescripcionVM[] | undefined;
    estadosOperacion?: Int16MaestroClaveCodigoDescripcionVM[] | undefined;
    conceptos?: Int16MaestroClaveCodigoDescripcionVM[] | undefined;
}

export interface ObtenerMunicipiosPorProvinciaQuery {
    codigoProvincia?: string | undefined;
}

export interface OperacionDTO {
    codExpediente?: string | undefined;
    titular?: string | undefined;
    tipoOperacion?: string | undefined;
    serieMandamiento?: string | undefined;
    numeroMandamiento?: string | undefined;
    fecha?: dayjs.Dayjs;
    importe?: number;
    moneda?: string | undefined;
    fechaCaducidad?: dayjs.Dayjs | undefined;
    numeroOperacion?: string | undefined;
}

export interface OrganoJudicialMaestroDTO {
    clave?: number;
    descripcion?: string | undefined;
    codigo?: string | undefined;
    descripcionLarga?: string | undefined;
    codigoPoblacion?: string | undefined;
    idOrdenJurisdiccional?: number;
    idTipoOrgano?: number;
}

export interface ProcedimientoVM {
    nig?: string | undefined;
    unidad_funcional?: string | undefined;
    jurisdiccion?: string | undefined;
    tipo?: string | undefined;
    codigo_procedimiento?: string | undefined;
    num_procedimiento?: string | undefined;
    subindice_pieza?: string | undefined;
    codigo_procedimiento_origen?: string | undefined;
    num_procedimiento_origen?: string | undefined;
}

export interface RelacionVM {
    cod_expediente?: string | undefined;
    modificable?: boolean;
    usuario_modif?: UsuarioModifVM;
    fecha_modif?: dayjs.Dayjs | undefined;
    procedimiento?: ProcedimientoVM;
}

export interface RelacionarCuentaExpedienteCommand {
    idExpedienteEncriptado?: string | undefined;
    codExpediente?: string | undefined;
}

export interface RelacionarCuentaExpedienteVM {
    resultadoErroneo?: boolean;
    error?: string | undefined;
}

export interface ResultadosDTO {
    fechaIngreso?: dayjs.Dayjs;
    fechaFirmeza?: dayjs.Dayjs;
    tipoMovimiento?: string | undefined;
    abono?: number;
    cargo?: number;
    moneda?: string | undefined;
    serieMandamiento?: string | undefined;
    numeroMandamiento?: string | undefined;
    numeroOperacion?: string | undefined;
}

export interface TotalesDTO {
    totalMoneda?: string | undefined;
    totalAbono?: number;
    totalPendiente?: number;
    totalCargo?: number;
}

export interface TransferenciaCECommand {
    datosTransferenciaCE?: DatosTransferenciaCECommandDTO;
}

export interface TransferenciaCEResponseVM {
    numOperacion?: string | undefined;
    numOperacionDestino?: string | undefined;
    codSeralfab?: string | undefined;
    numSr?: string | undefined;
    fecha?: dayjs.Dayjs;
    estado?: string | undefined;
    codRespuesta?: string | undefined;
    desRespuesta?: string | undefined;
    resultadoErroneo?: boolean;
    error?: string | undefined;
}

export interface TraspasoCECommand {
    datosTraspasoCE?: DatosTraspasoCECommandDTO;
}

export interface TraspasoCEResponseVM {
    numOperacion?: string | undefined;
    numOperacionDestino?: string | undefined;
    codSeralfab?: string | undefined;
    numSr?: string | undefined;
    fecha?: dayjs.Dayjs;
    importes?: Importes;
    monedas?: Monedas;
    estado?: string | undefined;
    codRespuesta?: string | undefined;
    desRespuesta?: string | undefined;
    resultadoErroneo?: boolean;
    error?: string | undefined;
}

export interface UsuarioModifVM {
    tip_documento?: string | undefined;
    cod_documento?: string | undefined;
    unidad_funcional_usu?: string | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}