//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.0.0 (NJsonSchema v11.5.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

export interface IAvisosClient {
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerSiHayAvisosCORPME(
    x_api_version?: string | undefined,
    body?: ObtenerSiHayAvisosCORPMEQuery | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerSiHayAvisosCORPMEResponse>;
}

export class AvisosClient implements IAvisosClient {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? '';
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerSiHayAvisosCORPME(
    x_api_version?: string | undefined,
    body?: ObtenerSiHayAvisosCORPMEQuery | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerSiHayAvisosCORPMEResponse> {
    let url_ = this.baseUrl + '/api/Avisos/ObtenerSiHayAvisosCORPME';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerSiHayAvisosCORPME(_response);
      });
  }

  protected processObtenerSiHayAvisosCORPME(
    response: AxiosResponse,
  ): Promise<ObtenerSiHayAvisosCORPMEResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerSiHayAvisosCORPMEResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerSiHayAvisosCORPMEResponse>(null as any);
  }
}

export interface IBuscadorClient {
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerMaestros(
    x_api_version?: string | undefined,
    body?: ObtenerMaestrosQuery_PresentacionesRegistro | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerMaestrosResponse_PresentacionesRegistro>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerResultados(
    x_api_version?: string | undefined,
    body?: ObtenerResultadosQuery_PresentacionesRegistro | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerResultadosResponse_PresentacionesRegistro>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  descartar(
    x_api_version?: string | undefined,
    body?: DescartarCommand | undefined,
    signal?: AbortSignal,
  ): Promise<DescartarResponse>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerMaestros2(
    x_api_version?: string | undefined,
    body?: ObtenerMaestrosQuery_Notificaciones | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerMaestrosResponse_Notificaciones>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerResultados2(
    x_api_version?: string | undefined,
    body?: ObtenerResultadosQuery_Notificaciones | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerResultadosResponse_Notificaciones>;
}

export class BuscadorClient implements IBuscadorClient {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? '';
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerMaestros(
    x_api_version?: string | undefined,
    body?: ObtenerMaestrosQuery_PresentacionesRegistro | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerMaestrosResponse_PresentacionesRegistro> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/presentacionesRegistro/buscador/ObtenerMaestros';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerMaestros(_response);
      });
  }

  protected processObtenerMaestros(
    response: AxiosResponse,
  ): Promise<ObtenerMaestrosResponse_PresentacionesRegistro> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerMaestrosResponse_PresentacionesRegistro>(
        result200,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerMaestrosResponse_PresentacionesRegistro>(
      null as any,
    );
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerResultados(
    x_api_version?: string | undefined,
    body?: ObtenerResultadosQuery_PresentacionesRegistro | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerResultadosResponse_PresentacionesRegistro> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/presentacionesRegistro/buscador/ObtenerResultados';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerResultados(_response);
      });
  }

  protected processObtenerResultados(
    response: AxiosResponse,
  ): Promise<ObtenerResultadosResponse_PresentacionesRegistro> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerResultadosResponse_PresentacionesRegistro>(
        result200,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerResultadosResponse_PresentacionesRegistro>(
      null as any,
    );
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  descartar(
    x_api_version?: string | undefined,
    body?: DescartarCommand | undefined,
    signal?: AbortSignal,
  ): Promise<DescartarResponse> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/presentacionesRegistro/buscador/Descartar';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processDescartar(_response);
      });
  }

  protected processDescartar(
    response: AxiosResponse,
  ): Promise<DescartarResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<DescartarResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<DescartarResponse>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerMaestros2(
    x_api_version?: string | undefined,
    body?: ObtenerMaestrosQuery_Notificaciones | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerMaestrosResponse_Notificaciones> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/notificaciones/buscador/ObtenerMaestros';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerMaestros2(_response);
      });
  }

  protected processObtenerMaestros2(
    response: AxiosResponse,
  ): Promise<ObtenerMaestrosResponse_Notificaciones> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerMaestrosResponse_Notificaciones>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerMaestrosResponse_Notificaciones>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerResultados2(
    x_api_version?: string | undefined,
    body?: ObtenerResultadosQuery_Notificaciones | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerResultadosResponse_Notificaciones> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/notificaciones/buscador/ObtenerResultados';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerResultados2(_response);
      });
  }

  protected processObtenerResultados2(
    response: AxiosResponse,
  ): Promise<ObtenerResultadosResponse_Notificaciones> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerResultadosResponse_Notificaciones>(
        result200,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerResultadosResponse_Notificaciones>(
      null as any,
    );
  }
}

export interface IDetalleClient {
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerMaestrosYDatos(
    x_api_version?: string | undefined,
    body?: ObtenerMaestrosYDatosQuery | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerMaestrosYDatosResponse>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerRegistrosProvincia(
    x_api_version?: string | undefined,
    body?: ObtenerRegistrosProvinciaCommand | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerRegistrosProvinciaResponse>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerMunicipiosProvincia(
    x_api_version?: string | undefined,
    body?: ObtenerMunicipiosProvinciaCommand | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerMunicipiosProvinciaResponse>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerProcuradoresExpediente(
    x_api_version?: string | undefined,
    body?: ObtenerProcuradoresExpedienteQuery | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerProcuradoresExpedienteResponse>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerIntervinientesExpediente(
    x_api_version?: string | undefined,
    body?: ObtenerIntervinientesExpedienteQuery | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerIntervinientesExpedienteResponse>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  guardar(
    x_api_version?: string | undefined,
    body?: GuardarCommand | undefined,
    signal?: AbortSignal,
  ): Promise<GuardarResponse>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerDatos(
    x_api_version?: string | undefined,
    body?: ObtenerDatosYMarcarVistoQuery | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerDatosYMarcarVistoResponse>;
}

export class DetalleClient implements IDetalleClient {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? '';
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerMaestrosYDatos(
    x_api_version?: string | undefined,
    body?: ObtenerMaestrosYDatosQuery | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerMaestrosYDatosResponse> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/presentacionesRegistro/detalle/ObtenerMaestrosYDatos';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerMaestrosYDatos(_response);
      });
  }

  protected processObtenerMaestrosYDatos(
    response: AxiosResponse,
  ): Promise<ObtenerMaestrosYDatosResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerMaestrosYDatosResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerMaestrosYDatosResponse>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerRegistrosProvincia(
    x_api_version?: string | undefined,
    body?: ObtenerRegistrosProvinciaCommand | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerRegistrosProvinciaResponse> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/presentacionesRegistro/detalle/ObtenerRegistrosProvincia';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerRegistrosProvincia(_response);
      });
  }

  protected processObtenerRegistrosProvincia(
    response: AxiosResponse,
  ): Promise<ObtenerRegistrosProvinciaResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerRegistrosProvinciaResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerRegistrosProvinciaResponse>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerMunicipiosProvincia(
    x_api_version?: string | undefined,
    body?: ObtenerMunicipiosProvinciaCommand | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerMunicipiosProvinciaResponse> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/presentacionesRegistro/detalle/ObtenerMunicipiosProvincia';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerMunicipiosProvincia(_response);
      });
  }

  protected processObtenerMunicipiosProvincia(
    response: AxiosResponse,
  ): Promise<ObtenerMunicipiosProvinciaResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerMunicipiosProvinciaResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerMunicipiosProvinciaResponse>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerProcuradoresExpediente(
    x_api_version?: string | undefined,
    body?: ObtenerProcuradoresExpedienteQuery | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerProcuradoresExpedienteResponse> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/presentacionesRegistro/detalle/ObtenerProcuradoresExpediente';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerProcuradoresExpediente(_response);
      });
  }

  protected processObtenerProcuradoresExpediente(
    response: AxiosResponse,
  ): Promise<ObtenerProcuradoresExpedienteResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerProcuradoresExpedienteResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerProcuradoresExpedienteResponse>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerIntervinientesExpediente(
    x_api_version?: string | undefined,
    body?: ObtenerIntervinientesExpedienteQuery | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerIntervinientesExpedienteResponse> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/presentacionesRegistro/detalle/ObtenerIntervinientesExpediente';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerIntervinientesExpediente(_response);
      });
  }

  protected processObtenerIntervinientesExpediente(
    response: AxiosResponse,
  ): Promise<ObtenerIntervinientesExpedienteResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerIntervinientesExpedienteResponse>(
        result200,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerIntervinientesExpedienteResponse>(
      null as any,
    );
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  guardar(
    x_api_version?: string | undefined,
    body?: GuardarCommand | undefined,
    signal?: AbortSignal,
  ): Promise<GuardarResponse> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/presentacionesRegistro/detalle/Guardar';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGuardar(_response);
      });
  }

  protected processGuardar(response: AxiosResponse): Promise<GuardarResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<GuardarResponse>(result200);
    } else if (status === 400) {
      const _responseText = response.data;
      let result400: any = null;
      let resultData400 = _responseText;
      result400 = JSON.parse(resultData400);
      return throwException(
        'Bad Request',
        status,
        _responseText,
        _headers,
        result400,
      );
    } else if (status === 401) {
      const _responseText = response.data;
      let result401: any = null;
      let resultData401 = _responseText;
      result401 = JSON.parse(resultData401);
      return throwException(
        'Unauthorized',
        status,
        _responseText,
        _headers,
        result401,
      );
    } else if (status === 403) {
      const _responseText = response.data;
      let result403: any = null;
      let resultData403 = _responseText;
      result403 = JSON.parse(resultData403);
      return throwException(
        'Forbidden',
        status,
        _responseText,
        _headers,
        result403,
      );
    } else if (status === 500) {
      const _responseText = response.data;
      let result500: any = null;
      let resultData500 = _responseText;
      result500 = JSON.parse(resultData500);
      return throwException(
        'Internal Server Error',
        status,
        _responseText,
        _headers,
        result500,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<GuardarResponse>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerDatos(
    x_api_version?: string | undefined,
    body?: ObtenerDatosYMarcarVistoQuery | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerDatosYMarcarVistoResponse> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/notificaciones/detalle/ObtenerDatos';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerDatos(_response);
      });
  }

  protected processObtenerDatos(
    response: AxiosResponse,
  ): Promise<ObtenerDatosYMarcarVistoResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerDatosYMarcarVistoResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerDatosYMarcarVistoResponse>(null as any);
  }
}

export interface IEnviosClient {
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  enviar(
    x_api_version?: string | undefined,
    body?: EnviarCommand | undefined,
    signal?: AbortSignal,
  ): Promise<EnviarResponse>;
}

export class EnviosClient implements IEnviosClient {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? '';
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  enviar(
    x_api_version?: string | undefined,
    body?: EnviarCommand | undefined,
    signal?: AbortSignal,
  ): Promise<EnviarResponse> {
    let url_ =
      this.baseUrl +
      '/api/privado/propiedad/presentacionesRegistro/envios/Enviar';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processEnviar(_response);
      });
  }

  protected processEnviar(response: AxiosResponse): Promise<EnviarResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      const _responseText = response.data;
      let result201: any = null;
      let resultData201 = _responseText;
      result201 = JSON.parse(resultData201);
      return Promise.resolve<EnviarResponse>(result201);
    } else if (status === 400) {
      const _responseText = response.data;
      let result400: any = null;
      let resultData400 = _responseText;
      result400 = JSON.parse(resultData400);
      return throwException(
        'Bad Request',
        status,
        _responseText,
        _headers,
        result400,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<EnviarResponse>(null as any);
  }
}

export interface INotificacionesClient {
  /**
   * @param x_api_version (optional)
   * @return OK
   */
  notificacion(
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<string>;
}

export class NotificacionesClient implements INotificacionesClient {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? '';
  }

  /**
   * @param x_api_version (optional)
   * @return OK
   */
  notificacion(
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<string> {
    let url_ = this.baseUrl + '/api/notificacion';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'text/plain',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processNotificacion(_response);
      });
  }

  protected processNotificacion(response: AxiosResponse): Promise<string> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = resultData200;
      return Promise.resolve<string>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<string>(null as any);
  }
}

export interface ArchivoVM {
  idArchivoEncriptado: string;
  titulo: string;
}

export interface BienInmuebleVM_Guardar {
  inmatriculado: boolean;
  idMedioIdentificacion?: number | undefined;
  codigoMunicipio?: string | undefined;
  seccionRegistral?: number | undefined;
  numeroFincaRegistral?: number | undefined;
  subnumeroFincaRegistral?: string | undefined;
  numeroFincaDuplicado?: number | undefined;
  idufir?: string | undefined;
  descripcionBienInmueble?: string | undefined;
  referenciaCatastral?: string | undefined;
}

export interface BienInmuebleVM_ObtenerMaestros {
  inmatriculado: boolean;
  idMedioIdentificacion: number | undefined;
  descripcionTipoIdentificacion: string | undefined;
  codigoMunicipio: string | undefined;
  codigoProvincia: string | undefined;
  seccionRegistral: number | undefined;
  numeroFincaRegistral: number | undefined;
  subnumeroFincaRegistral: string | undefined;
  numeroFincaDuplicado: number | undefined;
  idufir: string | undefined;
  descripcionBienInmueble: string | undefined;
  referenciaCatastral: string | undefined;
}

export interface CategoriaAvisosComunicacionesCORPMEVM {
  hayPresentacionesPropiedadConErrorEnvio: boolean;
  hayNotificacionesNoVistas: boolean;
}

export interface DescartarCommand {
  idPresentacionPropiedadEncriptado: string;
}

export interface DescartarResponse {
  descripcionesErrores: string[];
}

export interface DestinoVM_Guardar {
  idRegistro: number;
  idTipoOperacion: number;
  descripcion?: string | undefined;
}

export interface DestinoVM_ObtenerMaestrosYDatos {
  numeroEntrada: string | undefined;
  fechaEntrada: Date | undefined;
  codigoProvincia: string;
  idRegistro: number;
  idTipoOperacion: number;
  descripcion: string | undefined;
}

export interface DocumentoVM_PresentacionesRegistro {
  principal: boolean;
  idArchivoEncriptado: string | undefined;
  idDocumentoEncriptado: string | undefined;
  titulo: string;
  fecha: Date;
}

export interface EnviarCommand {
  idPresentacionPropiedadEncriptado: string;
}

export interface EnviarResponse {
  descripcionesErrores: string[];
}

export interface ErrorEnvioVM {
  esEditable: boolean;
  esReintentable: boolean;
  erroresAgrupadosPorLlamadaSalientePorComunicacionPorSolicitud: number;
}

export interface ExpedienteVM {
  descripcionOrgano: string;
  descripcionTipoProcedimiento: string;
  numeroProcedimiento: string;
  anoProcedimiento: string;
  numeroPieza: number;
}

export interface GuardarCommand {
  idExpedienteEncriptado?: string | undefined;
  idPresentacionPropiedadEncriptado?: string | undefined;
  idTipoEntradaPresentacionPropiedad: number;
  destino: DestinoVM_Guardar;
  idTipoPresentacion: number;
  idIntervinienteEncriptado?: string | undefined;
  bienesInmuebles: BienInmuebleVM_Guardar[];
  idDocumentoPrincipalEncriptado?: string | undefined;
  idsArchivosEncriptados: string[];
  registrarNueva: boolean;
}

export interface GuardarResponse {
  idPresentacionPropiedadCORPMEEncriptado: string;
  descripcionesErrores: string[];
}

export interface IntervinienteExpedienteVM {
  idIntervinienteEncriptado: string;
  descripcionTipoIntervencion: string;
  nombre: string;
  apellido1: string;
  apellido2: string | undefined;
  identificacion: string | undefined;
}

export interface MaestroClaveDescripcionVM_Int16 {
  clave: number;
  descripcion: string;
}

export interface MaestroClaveDescripcionVM_Int32 {
  clave: number;
  descripcion: string;
}

export interface MaestroClaveDescripcionVM_String {
  clave: string | undefined;
  descripcion: string;
}

export interface MaestrosVM {
  provincias: MaestroClaveDescripcionVM_String[];
  tiposOperacion: MaestroClaveDescripcionVM_Int16[];
}

export interface NotificacionVM {
  idNotificacionEncriptado: string;
  numeroEntrada: string | undefined;
  nombreRegistroDestino: string;
  descripcionTipoNotificacion: string;
  fechaNotificacion: Date;
  descripcionEstado: string;
  idExpedienteEncriptado: string;
  numeroProcedimiento: string;
  anoProcedimiento: string;
  numeroPiezaProcedimiento: string;
  codigoTipoProcedimiento: string;
  nombreLetradoExpediente: string | undefined;
  apellido1LetradoExpediente: string | undefined;
  apellido2LetradoExpediente: string | undefined;
  seccion: string | undefined;
  descripcionOrganoJudicialPlaza: string | undefined;
  visto: boolean;
}

export interface ObtenerDatosYMarcarVistoQuery {
  idNotificacionEncriptado: string;
}

export interface ObtenerDatosYMarcarVistoResponse {
  numeroAnoEntrada: string;
  nombreRegistroDestino: string;
  descripcionTipoNotificacion: string;
  identificadorTramiteCORPME: string;
  fechaNotificacion: Date;
  fechaVisto: Date;
  fechaCaducidad: Date | undefined;
  archivos: ArchivoVM[];
  idExpedienteEncriptado: string;
}

export interface ObtenerIntervinientesExpedienteQuery {
  idExpedienteEncriptado: string;
}

export interface ObtenerIntervinientesExpedienteResponse {
  intervinientesExpediente: IntervinienteExpedienteVM[];
}

export interface ObtenerMaestrosQuery_Notificaciones {}

export interface ObtenerMaestrosQuery_PresentacionesRegistro {}

export interface ObtenerMaestrosResponse_Notificaciones {
  organos: MaestroClaveDescripcionVM_Int32[];
  registros: MaestroClaveDescripcionVM_Int16[];
  tiposNotificaciones: MaestroClaveDescripcionVM_Int16[];
  estados: MaestroClaveDescripcionVM_Int16[];
  esSeccion: boolean;
  esPlaza: boolean;
}

export interface ObtenerMaestrosResponse_PresentacionesRegistro {
  organos: MaestroClaveDescripcionVM_Int32[];
  registros: MaestroClaveDescripcionVM_Int16[];
  tiposOperaciones: MaestroClaveDescripcionVM_Int16[];
  estados: MaestroClaveDescripcionVM_Int16[];
  letrados: MaestroClaveDescripcionVM_Int32[];
  esSeccion: boolean;
  esPlaza: boolean;
}

export interface ObtenerMaestrosYDatosQuery {
  idExpedienteEncriptado: string;
  idPresentacionPropiedadEncriptado?: string | undefined;
  registrarNueva: boolean;
}

export interface ObtenerMaestrosYDatosResponse {
  maestros: MaestrosVM;
  expediente: ExpedienteVM;
  registroPropiedad: RegistroPropiedadVM;
  estadoPresentacion: number | undefined;
  errorEnvio: ErrorEnvioVM;
}

export interface ObtenerMunicipiosProvinciaCommand {
  codigoProvincia: string;
}

export interface ObtenerMunicipiosProvinciaResponse {
  municipios: MaestroClaveDescripcionVM_String[];
}

export interface ObtenerProcuradoresExpedienteQuery {
  idExpedienteEncriptado: string;
}

export interface ObtenerProcuradoresExpedienteResponse {
  procuradoresExpediente: ProcuradorVM[];
}

export interface ObtenerRegistrosProvinciaCommand {
  codigoProvincia: string;
}

export interface ObtenerRegistrosProvinciaResponse {
  registros: MaestroClaveDescripcionVM_Int16[];
}

export interface ObtenerResultadosQuery_Notificaciones {
  idRegistro?: number | undefined;
  idTipoNotificacion?: number | undefined;
  numeroEntrada?: string | undefined;
  anoEntrada?: string | undefined;
  idOrganoJudicialPlaza?: string | undefined;
  numeroProcedimiento?: string | undefined;
  anoProcedimiento?: string | undefined;
  idEstado?: number | undefined;
  fechaNotificacionDesde?: Date | undefined;
  fechaNotificacionHasta?: Date | undefined;
  visto?: boolean | undefined;
}

export interface ObtenerResultadosQuery_PresentacionesRegistro {
  idRegistro?: number | undefined;
  idTipoOperacion?: number | undefined;
  idEstado?: number | undefined;
  fechaEstadoDesde?: Date | undefined;
  fechaEstadoHasta?: Date | undefined;
  numeroEntrada?: string | undefined;
  anoEntrada?: string | undefined;
  numeroProcedimiento?: string | undefined;
  anoProcedimiento?: string | undefined;
  idOrganoJudicialPlaza?: number | undefined;
  idLetrado?: number | undefined;
}

export interface ObtenerResultadosResponse_Notificaciones {
  notificaciones: NotificacionVM[];
  seHaSuperadoMaximoNumeroResultados: boolean;
}

export interface ObtenerResultadosResponse_PresentacionesRegistro {
  presentaciones: PresentacionRegistroVM[];
  seHaSuperadoMaximoNumeroResultados: boolean;
}

export interface ObtenerSiHayAvisosCORPMEQuery {}

export interface ObtenerSiHayAvisosCORPMEResponse {
  comunicacionesCORPME: CategoriaAvisosComunicacionesCORPMEVM;
  success: boolean;
}

export interface PresentacionRegistroVM {
  idPresentacionEncriptado: string;
  numeroEntrada: string | undefined;
  nombreRegistroDestino: string;
  descripcionTipoActuacion: string;
  fechaEstado: Date;
  idEstado: number;
  descripcionEstado: string;
  idExpedienteEncriptado: string;
  numeroProcedimiento: string;
  anoProcedimiento: string;
  numeroPiezaProcedimiento: string;
  codigoTipoProcedimiento: string;
  nombreLetradoExpediente: string | undefined;
  apellido1LetradoExpediente: string | undefined;
  apellido2LetradoExpediente: string | undefined;
  seccion: string | undefined;
  descripcionOrganoJudicialPlaza: string | undefined;
  esSubsanacion: boolean;
}

export interface PresentanteIntervinienteVM {
  idIntervinienteEncriptado: string;
  descripcionTipoIntervencion: string;
  nombre: string;
  apellido1: string;
  apellido2: string | undefined;
  identificacion: string | undefined;
}

export interface PresentanteProcuradorVM {
  idIntervinienteEncriptado: string;
  nombreInterviniente: string;
  apellido1Interviniente: string;
  apellido2Interviniente: string | undefined;
  nombreProcurador: string | undefined;
  apellido1Procurador: string | undefined;
  apellido2Procurador: string | undefined;
  descripcionTipoInterviniente: string;
}

export interface ProblemDetails {
  type?: string | undefined;
  title?: string | undefined;
  status?: number | undefined;
  detail?: string | undefined;
  instance?: string | undefined;

  [key: string]: any;
}

export interface ProcuradorVM {
  idIntervinienteEncriptado: string;
  nombreInterviniente: string;
  apellido1Interviniente: string;
  apellido2Interviniente: string | undefined;
  nombreProcurador: string | undefined;
  apellido1Procurador: string | undefined;
  apellido2Procurador: string | undefined;
  descripcionTipoIntervencion: string;
}

export interface RegistroPropiedadVM {
  destino: DestinoVM_ObtenerMaestrosYDatos;
  idTipoPresentacion: number;
  idTipoEntradaPresentacion: number;
  identificadorTramite: string;
  descripcionEstadoPresentacion: string;
  presentanteProcurador: PresentanteProcuradorVM;
  presentanteInterviniente: PresentanteIntervinienteVM;
  bienesInmuebles: BienInmuebleVM_ObtenerMaestros[];
  documentos: DocumentoVM_PresentacionesRegistro[];
}

export interface ValidationProblemDetails {
  type?: string | undefined;
  title?: string | undefined;
  status?: number | undefined;
  detail?: string | undefined;
  instance?: string | undefined;
  errors: { [key: string]: string[] };

  [key: string]: any;
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any,
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  if (result !== null && result !== undefined) throw result;
  else throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
  return obj && obj.isAxiosError === true;
}
