//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import axios, { AxiosError } from 'axios';

import dayjs from 'dayjs';

export interface IAsientosClient {
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  confirmarAsiento(
    x_api_version?: string | undefined,
    body?: ConfirmarAsientoCommand | undefined,
  ): Promise<IActionResult>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  rechazarAsiento(
    x_api_version?: string | undefined,
    body?: RechazarAsientoCommand | undefined,
  ): Promise<IActionResult>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  redirigirAsiento(
    x_api_version?: string | undefined,
    body?: RedirigirAsientoCommand | undefined,
  ): Promise<IActionResult>;
}

export class AsientosClient implements IAsientosClient {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? '';
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  confirmarAsiento(
    x_api_version?: string | undefined,
    body?: ConfirmarAsientoCommand | undefined,
    signal?: AbortSignal,
  ): Promise<IActionResult> {
    let url_ = this.baseUrl + '/api/asientos/ConfirmarAsiento';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'text/plain',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processConfirmarAsiento(_response);
      });
  }

  protected processConfirmarAsiento(
    response: AxiosResponse,
  ): Promise<IActionResult> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      const _responseText = response.data;
      let result201: any = null;
      let resultData201 = _responseText;
      result201 = JSON.parse(resultData201);
      return Promise.resolve<IActionResult>(result201);
    } else if (status === 400) {
      const _responseText = response.data;
      let result400: any = null;
      let resultData400 = _responseText;
      result400 = JSON.parse(resultData400);
      return throwException(
        'Bad Request',
        status,
        _responseText,
        _headers,
        result400,
      );
    } else if (status === 401) {
      const _responseText = response.data;
      let result401: any = null;
      let resultData401 = _responseText;
      result401 = JSON.parse(resultData401);
      return throwException(
        'Unauthorized',
        status,
        _responseText,
        _headers,
        result401,
      );
    } else if (status === 403) {
      const _responseText = response.data;
      let result403: any = null;
      let resultData403 = _responseText;
      result403 = JSON.parse(resultData403);
      return throwException(
        'Forbidden',
        status,
        _responseText,
        _headers,
        result403,
      );
    } else if (status === 500) {
      const _responseText = response.data;
      let result500: any = null;
      let resultData500 = _responseText;
      result500 = JSON.parse(resultData500);
      return throwException(
        'Internal Server Error',
        status,
        _responseText,
        _headers,
        result500,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<IActionResult>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  rechazarAsiento(
    x_api_version?: string | undefined,
    body?: RechazarAsientoCommand | undefined,
    signal?: AbortSignal,
  ): Promise<IActionResult> {
    let url_ = this.baseUrl + '/api/asientos/RechazarAsiento';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'text/plain',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processRechazarAsiento(_response);
      });
  }

  protected processRechazarAsiento(
    response: AxiosResponse,
  ): Promise<IActionResult> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      const _responseText = response.data;
      let result201: any = null;
      let resultData201 = _responseText;
      result201 = JSON.parse(resultData201);
      return Promise.resolve<IActionResult>(result201);
    } else if (status === 400) {
      const _responseText = response.data;
      let result400: any = null;
      let resultData400 = _responseText;
      result400 = JSON.parse(resultData400);
      return throwException(
        'Bad Request',
        status,
        _responseText,
        _headers,
        result400,
      );
    } else if (status === 401) {
      const _responseText = response.data;
      let result401: any = null;
      let resultData401 = _responseText;
      result401 = JSON.parse(resultData401);
      return throwException(
        'Unauthorized',
        status,
        _responseText,
        _headers,
        result401,
      );
    } else if (status === 403) {
      const _responseText = response.data;
      let result403: any = null;
      let resultData403 = _responseText;
      result403 = JSON.parse(resultData403);
      return throwException(
        'Forbidden',
        status,
        _responseText,
        _headers,
        result403,
      );
    } else if (status === 500) {
      const _responseText = response.data;
      let result500: any = null;
      let resultData500 = _responseText;
      result500 = JSON.parse(resultData500);
      return throwException(
        'Internal Server Error',
        status,
        _responseText,
        _headers,
        result500,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<IActionResult>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  redirigirAsiento(
    x_api_version?: string | undefined,
    body?: RedirigirAsientoCommand | undefined,
    signal?: AbortSignal,
  ): Promise<IActionResult> {
    let url_ = this.baseUrl + '/api/asientos/RedirigirAsiento';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'text/plain',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processRedirigirAsiento(_response);
      });
  }

  protected processRedirigirAsiento(
    response: AxiosResponse,
  ): Promise<IActionResult> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      const _responseText = response.data;
      let result201: any = null;
      let resultData201 = _responseText;
      result201 = JSON.parse(resultData201);
      return Promise.resolve<IActionResult>(result201);
    } else if (status === 400) {
      const _responseText = response.data;
      let result400: any = null;
      let resultData400 = _responseText;
      result400 = JSON.parse(resultData400);
      return throwException(
        'Bad Request',
        status,
        _responseText,
        _headers,
        result400,
      );
    } else if (status === 401) {
      const _responseText = response.data;
      let result401: any = null;
      let resultData401 = _responseText;
      result401 = JSON.parse(resultData401);
      return throwException(
        'Unauthorized',
        status,
        _responseText,
        _headers,
        result401,
      );
    } else if (status === 403) {
      const _responseText = response.data;
      let result403: any = null;
      let resultData403 = _responseText;
      result403 = JSON.parse(resultData403);
      return throwException(
        'Forbidden',
        status,
        _responseText,
        _headers,
        result403,
      );
    } else if (status === 500) {
      const _responseText = response.data;
      let result500: any = null;
      let resultData500 = _responseText;
      result500 = JSON.parse(resultData500);
      return throwException(
        'Internal Server Error',
        status,
        _responseText,
        _headers,
        result500,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<IActionResult>(null as any);
  }
}

export interface IEnviosClient {
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  guardarEnvio(
    x_api_version?: string | undefined,
    body?: GuardarEnvioCommand | undefined,
  ): Promise<GuardarEnvioResponse>;
  /**
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerDestinosFavoritos(
    x_api_version?: string | undefined,
  ): Promise<ObtenerDestinosFavoritosResponse>;
  /**
   * @param idAsientoEncriptado (optional)
   * @param idApunteEncriptado (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerDetalleEnvio(
    idAsientoEncriptado?: string | undefined,
    idApunteEncriptado?: string | undefined,
    x_api_version?: string | undefined,
  ): Promise<ObtenerDetalleEnvioResponse>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerEnvios(
    x_api_version?: string | undefined,
    body?: ObtenerEnviosQuery | undefined,
  ): Promise<ObtenerEnviosResponse>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerEnvios(
    x_api_version?: string | undefined,
    body?: ObtenerEnviosQuery | undefined,
  ): Promise<ObtenerEnviosResponse>;
}

export class EnviosClient implements IEnviosClient {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? '';
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  guardarEnvio(
    x_api_version?: string | undefined,
    body?: GuardarEnvioCommand | undefined,
    signal?: AbortSignal,
  ): Promise<GuardarEnvioResponse> {
    let url_ = this.baseUrl + '/api/envios/GuardarEnvio';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'text/plain',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processGuardarEnvio(_response);
      });
  }

  protected processGuardarEnvio(
    response: AxiosResponse,
  ): Promise<GuardarEnvioResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      const _responseText = response.data;
      let result201: any = null;
      let resultData201 = _responseText;
      result201 = JSON.parse(resultData201);
      return Promise.resolve<GuardarEnvioResponse>(result201);
    } else if (status === 400) {
      const _responseText = response.data;
      let result400: any = null;
      let resultData400 = _responseText;
      result400 = JSON.parse(resultData400);
      return throwException(
        'Bad Request',
        status,
        _responseText,
        _headers,
        result400,
      );
    } else if (status === 401) {
      const _responseText = response.data;
      let result401: any = null;
      let resultData401 = _responseText;
      result401 = JSON.parse(resultData401);
      return throwException(
        'Unauthorized',
        status,
        _responseText,
        _headers,
        result401,
      );
    } else if (status === 403) {
      const _responseText = response.data;
      let result403: any = null;
      let resultData403 = _responseText;
      result403 = JSON.parse(resultData403);
      return throwException(
        'Forbidden',
        status,
        _responseText,
        _headers,
        result403,
      );
    } else if (status === 500) {
      const _responseText = response.data;
      let result500: any = null;
      let resultData500 = _responseText;
      result500 = JSON.parse(resultData500);
      return throwException(
        'Internal Server Error',
        status,
        _responseText,
        _headers,
        result500,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<GuardarEnvioResponse>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerDestinosFavoritos(
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerDestinosFavoritosResponse> {
    let url_ = this.baseUrl + '/api/envios/ObtenerDestinosFavoritos';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'text/plain',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerDestinosFavoritos(_response);
      });
  }

  protected processObtenerDestinosFavoritos(
    response: AxiosResponse,
  ): Promise<ObtenerDestinosFavoritosResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerDestinosFavoritosResponse>(result200);
    } else if (status === 400) {
      const _responseText = response.data;
      let result400: any = null;
      let resultData400 = _responseText;
      result400 = JSON.parse(resultData400);
      return throwException(
        'Bad Request',
        status,
        _responseText,
        _headers,
        result400,
      );
    } else if (status === 401) {
      const _responseText = response.data;
      let result401: any = null;
      let resultData401 = _responseText;
      result401 = JSON.parse(resultData401);
      return throwException(
        'Unauthorized',
        status,
        _responseText,
        _headers,
        result401,
      );
    } else if (status === 403) {
      const _responseText = response.data;
      let result403: any = null;
      let resultData403 = _responseText;
      result403 = JSON.parse(resultData403);
      return throwException(
        'Forbidden',
        status,
        _responseText,
        _headers,
        result403,
      );
    } else if (status === 500) {
      const _responseText = response.data;
      let result500: any = null;
      let resultData500 = _responseText;
      result500 = JSON.parse(resultData500);
      return throwException(
        'Internal Server Error',
        status,
        _responseText,
        _headers,
        result500,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerDestinosFavoritosResponse>(null as any);
  }

  /**
   * @param idAsientoEncriptado (optional)
   * @param idApunteEncriptado (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerDetalleEnvio(
    idAsientoEncriptado?: string | undefined,
    idApunteEncriptado?: string | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerDetalleEnvioResponse> {
    let url_ = this.baseUrl + '/api/envios/ObtenerDetalleEnvio?';
    if (idAsientoEncriptado === null)
      throw new Error("The parameter 'idAsientoEncriptado' cannot be null.");
    else if (idAsientoEncriptado !== undefined)
      url_ +=
        'idAsientoEncriptado=' +
        encodeURIComponent('' + idAsientoEncriptado) +
        '&';
    if (idApunteEncriptado === null)
      throw new Error("The parameter 'idApunteEncriptado' cannot be null.");
    else if (idApunteEncriptado !== undefined)
      url_ +=
        'idApunteEncriptado=' +
        encodeURIComponent('' + idApunteEncriptado) +
        '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'text/plain',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerDetalleEnvio(_response);
      });
  }

  protected processObtenerDetalleEnvio(
    response: AxiosResponse,
  ): Promise<ObtenerDetalleEnvioResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerDetalleEnvioResponse>(result200);
    } else if (status === 400) {
      const _responseText = response.data;
      let result400: any = null;
      let resultData400 = _responseText;
      result400 = JSON.parse(resultData400);
      return throwException(
        'Bad Request',
        status,
        _responseText,
        _headers,
        result400,
      );
    } else if (status === 401) {
      const _responseText = response.data;
      let result401: any = null;
      let resultData401 = _responseText;
      result401 = JSON.parse(resultData401);
      return throwException(
        'Unauthorized',
        status,
        _responseText,
        _headers,
        result401,
      );
    } else if (status === 403) {
      const _responseText = response.data;
      let result403: any = null;
      let resultData403 = _responseText;
      result403 = JSON.parse(resultData403);
      return throwException(
        'Forbidden',
        status,
        _responseText,
        _headers,
        result403,
      );
    } else if (status === 500) {
      const _responseText = response.data;
      let result500: any = null;
      let resultData500 = _responseText;
      result500 = JSON.parse(resultData500);
      return throwException(
        'Internal Server Error',
        status,
        _responseText,
        _headers,
        result500,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerDetalleEnvioResponse>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  obtenerEnvios(
    x_api_version?: string | undefined,
    body?: ObtenerEnviosQuery | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerEnviosResponse> {
    let url_ = this.baseUrl + '/api/envios/ObtenerEnvios';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'text/plain',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerEnvios(_response);
      });
  }

  protected processObtenerEnvios(
    response: AxiosResponse,
  ): Promise<ObtenerEnviosResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerEnviosResponse>(result200);
    } else if (status === 400) {
      const _responseText = response.data;
      let result400: any = null;
      let resultData400 = _responseText;
      result400 = JSON.parse(resultData400);
      return throwException(
        'Bad Request',
        status,
        _responseText,
        _headers,
        result400,
      );
    } else if (status === 401) {
      const _responseText = response.data;
      let result401: any = null;
      let resultData401 = _responseText;
      result401 = JSON.parse(resultData401);
      return throwException(
        'Unauthorized',
        status,
        _responseText,
        _headers,
        result401,
      );
    } else if (status === 403) {
      const _responseText = response.data;
      let result403: any = null;
      let resultData403 = _responseText;
      result403 = JSON.parse(resultData403);
      return throwException(
        'Forbidden',
        status,
        _responseText,
        _headers,
        result403,
      );
    } else if (status === 500) {
      const _responseText = response.data;
      let result500: any = null;
      let resultData500 = _responseText;
      result500 = JSON.parse(resultData500);
      return throwException(
        'Internal Server Error',
        status,
        _responseText,
        _headers,
        result500,
      );
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerEnviosResponse>(null as any);
  }
}

export interface ArchivoVM {
  idArchivoEncriptado: string | undefined;
  nombre?: string | undefined;
  tipoArchivo?: string | undefined;
  fechaArchivo?: string | undefined;
  icono?: number | undefined;
}

export interface ConfirmarAsientoCommand {
  idApunteEncriptado: string | undefined;
}

export interface DatosEnvioBuscadorVM {
  idAsientoEncriptado?: string | undefined;
  idApunteEncriptado?: string | undefined;
  estado?: string | undefined;
  expedienteOrigen?: string | undefined;
  administracion: string | undefined;
  fechaEnvio?: dayjs.Dayjs | undefined;
  fechaEstado?: dayjs.Dayjs | undefined;
  destinoRedireccion?: string | undefined;
  permiteRedireccion?: boolean;
}

export interface DestinoFavoritoVM {
  diR3: string | undefined;
  descripcion: string | undefined;
}

export interface GuardarEnvioCommand {
  idExpedienteEncriptado: string | undefined;
  nombreDestinatario: string | undefined;
  codigoOrganoJudicialDestinatario: string | undefined;
  archivos: ArchivoVM[] | undefined;
}

export interface GuardarEnvioResponse {
  idAsientoEncriptado: string | undefined;
}

export interface IActionResult {}

export interface ObtenerDestinosFavoritosResponse {
  destinosFavoritos?: DestinoFavoritoVM[] | undefined;
}

export interface ObtenerDetalleEnvioResponse {
  descripcionOrganoJudicialRemitente?: string | undefined;
  numeroRegistro?: string | undefined;
  destinatario?: string | undefined;
  estado: string | undefined;
  codigoDestinatario?: string | undefined;
  fechaEnvio?: dayjs.Dayjs | undefined;
  fechaRegistro?: dayjs.Dayjs | undefined;
  archivos?: ArchivoVM[] | undefined;
  permiteRedireccion: boolean;
  permiteRechazoAceptacion: boolean;
}

export interface ObtenerEnviosQuery {
  idTipoBusquedaEnvios: number;
  administracionEmisora?: string | undefined;
  fechaEnvioInicio?: dayjs.Dayjs | undefined;
  fechaEnvioFin?: dayjs.Dayjs | undefined;
  enviosRedirigidos: boolean;
}

export interface ObtenerEnviosResponse {
  envios: DatosEnvioBuscadorVM[] | undefined;
}

export interface ProblemDetails {
  type?: string | undefined;
  title?: string | undefined;
  status?: number | undefined;
  detail?: string | undefined;
  instance?: string | undefined;

  [key: string]: any;
}

export interface RechazarAsientoCommand {
  idApunteEncriptado: string | undefined;
}

export interface RedirigirAsientoCommand {
  idApunteEncriptado: string | undefined;
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any,
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  if (result !== null && result !== undefined) throw result;
  else throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
  return obj && obj.isAxiosError === true;
}
