//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

export interface IComunicacionDirectaClient {
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  enviarMensaje(
    x_api_version?: string | undefined,
    body?: EnviarMensajeCommand | undefined,
    signal?: AbortSignal,
  ): Promise<string>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  archivarComunicacionesDirectas(
    x_api_version?: string | undefined,
    body?: ArchivarConversacionesCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  actualizarConsentimientoComunicaciones(
    x_api_version?: string | undefined,
    body?: ActualizarConsentimientoComunicacionesCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void>;
  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  comprobarConsentimientoComunicaciones(
    request?: ComprobarConsentimientoComunicacionesQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<boolean>;
  /**
   * @param activas (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerConversacionesPorUsuario(
    activas?: boolean | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<ConversacionesPorUsuarioResponse>;
  /**
   * @param idConversacionEncriptado (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerMensajesPorConversacion(
    idConversacionEncriptado?: string | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<MensajesPorConversacionResponse>;
  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerConversacionesConMensajesNuevos(
    request?: ObtenerConversacionesConMensajesNuevosQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<string[]>;
  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerArchivadasConMensajesNuevos(
    request?: ObtenerArchivadasConMensajesNuevosQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<number>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  marcarMensajesLeidos(
    x_api_version?: string | undefined,
    body?: MarcarMensajesLeidosCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  asignarArchivoAMensaje(
    x_api_version?: string | undefined,
    body?: AsignarArchivoAMensajeCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void>;
}

export class ComunicacionDirectaClient implements IComunicacionDirectaClient {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? '';
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  enviarMensaje(
    x_api_version?: string | undefined,
    body?: EnviarMensajeCommand | undefined,
    signal?: AbortSignal,
  ): Promise<string> {
    let url_ = this.baseUrl + '/api/ComunicacionDirecta/EnviarMensaje';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processEnviarMensaje(_response);
      });
  }

  protected processEnviarMensaje(response: AxiosResponse): Promise<string> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      const _responseText = response.data;
      let result201: any = null;
      let resultData201 = _responseText;
      result201 = JSON.parse(resultData201);
      return Promise.resolve<string>(result201);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<string>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  archivarComunicacionesDirectas(
    x_api_version?: string | undefined,
    body?: ArchivarConversacionesCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ =
      this.baseUrl + '/api/ComunicacionDirecta/ArchivarComunicacionesDirectas';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processArchivarComunicacionesDirectas(_response);
      });
  }

  protected processArchivarComunicacionesDirectas(
    response: AxiosResponse,
  ): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  actualizarConsentimientoComunicaciones(
    x_api_version?: string | undefined,
    body?: ActualizarConsentimientoComunicacionesCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirecta/ActualizarConsentimientoComunicaciones';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processActualizarConsentimientoComunicaciones(_response);
      });
  }

  protected processActualizarConsentimientoComunicaciones(
    response: AxiosResponse,
  ): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  comprobarConsentimientoComunicaciones(
    request?: ComprobarConsentimientoComunicacionesQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<boolean> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirecta/ComprobarConsentimientoComunicaciones?';
    if (request === null)
      throw new globalThis.Error("The parameter 'request' cannot be null.");
    else if (request !== undefined)
      url_ += 'request=' + encodeURIComponent('' + request) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processComprobarConsentimientoComunicaciones(_response);
      });
  }

  protected processComprobarConsentimientoComunicaciones(
    response: AxiosResponse,
  ): Promise<boolean> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<boolean>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<boolean>(null as any);
  }

  /**
   * @param activas (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerConversacionesPorUsuario(
    activas?: boolean | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<ConversacionesPorUsuarioResponse> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirecta/ObtenerConversacionesPorUsuario?';
    if (activas === null)
      throw new globalThis.Error("The parameter 'activas' cannot be null.");
    else if (activas !== undefined)
      url_ += 'Activas=' + encodeURIComponent('' + activas) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerConversacionesPorUsuario(_response);
      });
  }

  protected processObtenerConversacionesPorUsuario(
    response: AxiosResponse,
  ): Promise<ConversacionesPorUsuarioResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ConversacionesPorUsuarioResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ConversacionesPorUsuarioResponse>(null as any);
  }

  /**
   * @param idConversacionEncriptado (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerMensajesPorConversacion(
    idConversacionEncriptado?: string | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<MensajesPorConversacionResponse> {
    let url_ =
      this.baseUrl + '/api/ComunicacionDirecta/ObtenerMensajesPorConversacion?';
    if (idConversacionEncriptado === null)
      throw new globalThis.Error(
        "The parameter 'idConversacionEncriptado' cannot be null.",
      );
    else if (idConversacionEncriptado !== undefined)
      url_ +=
        'IdConversacionEncriptado=' +
        encodeURIComponent('' + idConversacionEncriptado) +
        '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerMensajesPorConversacion(_response);
      });
  }

  protected processObtenerMensajesPorConversacion(
    response: AxiosResponse,
  ): Promise<MensajesPorConversacionResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<MensajesPorConversacionResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<MensajesPorConversacionResponse>(null as any);
  }

  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerConversacionesConMensajesNuevos(
    request?: ObtenerConversacionesConMensajesNuevosQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<string[]> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirecta/ObtenerConversacionesConMensajesNuevos?';
    if (request === null)
      throw new globalThis.Error("The parameter 'request' cannot be null.");
    else if (request !== undefined)
      url_ += 'request=' + encodeURIComponent('' + request) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerConversacionesConMensajesNuevos(_response);
      });
  }

  protected processObtenerConversacionesConMensajesNuevos(
    response: AxiosResponse,
  ): Promise<string[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<string[]>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<string[]>(null as any);
  }

  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerArchivadasConMensajesNuevos(
    request?: ObtenerArchivadasConMensajesNuevosQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<number> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirecta/ObtenerArchivadasConMensajesNuevos?';
    if (request === null)
      throw new globalThis.Error("The parameter 'request' cannot be null.");
    else if (request !== undefined)
      url_ += 'request=' + encodeURIComponent('' + request) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerArchivadasConMensajesNuevos(_response);
      });
  }

  protected processObtenerArchivadasConMensajesNuevos(
    response: AxiosResponse,
  ): Promise<number> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<number>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<number>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  marcarMensajesLeidos(
    x_api_version?: string | undefined,
    body?: MarcarMensajesLeidosCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/ComunicacionDirecta/MarcarMensajesLeidos';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processMarcarMensajesLeidos(_response);
      });
  }

  protected processMarcarMensajesLeidos(
    response: AxiosResponse,
  ): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  asignarArchivoAMensaje(
    x_api_version?: string | undefined,
    body?: AsignarArchivoAMensajeCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ = this.baseUrl + '/api/ComunicacionDirecta/AsignarArchivoAMensaje';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processAsignarArchivoAMensaje(_response);
      });
  }

  protected processAsignarArchivoAMensaje(
    response: AxiosResponse,
  ): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }
}

export interface IComunicacionDirectaPSPClient {
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  crearComunicacionDirecta(
    x_api_version?: string | undefined,
    body?: CrearComunicacionDirectaConElMagistradoCommand | undefined,
    signal?: AbortSignal,
  ): Promise<string>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  enviarMensaje2(
    x_api_version?: string | undefined,
    body?: EnviarMensajeCommand | undefined,
    signal?: AbortSignal,
  ): Promise<string>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  archivarComunicacionesDirectas2(
    x_api_version?: string | undefined,
    body?: ArchivarConversacionesCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  archivarComunicacionesDirectasPorUsuario(
    x_api_version?: string | undefined,
    body?: ArchivarComunicacionesDirectasPorUsuarioCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void>;
  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerOrganosJudicialesDisponiblesParaComunicacion(
    request?: ObtenerPlazasDisponiblesParaComunicacionQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerPlazasDisponiblesResponse>;
  /**
   * @param activas (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerConversacionesPorUsuario2(
    activas?: boolean | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<ConversacionesPorUsuarioResponse>;
  /**
   * @param idConversacionEncriptado (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerMensajesPorConversacion2(
    idConversacionEncriptado?: string | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<MensajesPorConversacionResponse>;
  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerConversacionesConMensajesNuevos2(
    request?: ObtenerConversacionesConMensajesNuevosQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<string[]>;
  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerArchivadasConMensajesNuevos2(
    request?: ObtenerArchivadasConMensajesNuevosQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<number>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  marcarMensajesLeidos2(
    x_api_version?: string | undefined,
    body?: MarcarMensajesLeidosCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void>;
  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  comprobarComunicacionesActivadas(
    request?: ComprobarComunicacionesActivadasQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<boolean>;
  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  asignarArchivoAMensaje2(
    x_api_version?: string | undefined,
    body?: AsignarArchivoAMensajeCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void>;
}

export class ComunicacionDirectaPSPClient
  implements IComunicacionDirectaPSPClient
{
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? '';
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return OK
   */
  crearComunicacionDirecta(
    x_api_version?: string | undefined,
    body?: CrearComunicacionDirectaConElMagistradoCommand | undefined,
    signal?: AbortSignal,
  ): Promise<string> {
    let url_ =
      this.baseUrl + '/api/ComunicacionDirectaPSP/CrearComunicacionDirecta';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processCrearComunicacionDirecta(_response);
      });
  }

  protected processCrearComunicacionDirecta(
    response: AxiosResponse,
  ): Promise<string> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<string>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<string>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  enviarMensaje2(
    x_api_version?: string | undefined,
    body?: EnviarMensajeCommand | undefined,
    signal?: AbortSignal,
  ): Promise<string> {
    let url_ = this.baseUrl + '/api/ComunicacionDirectaPSP/EnviarMensaje';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processEnviarMensaje2(_response);
      });
  }

  protected processEnviarMensaje2(response: AxiosResponse): Promise<string> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      const _responseText = response.data;
      let result201: any = null;
      let resultData201 = _responseText;
      result201 = JSON.parse(resultData201);
      return Promise.resolve<string>(result201);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<string>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  archivarComunicacionesDirectas2(
    x_api_version?: string | undefined,
    body?: ArchivarConversacionesCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirectaPSP/ArchivarComunicacionesDirectas';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processArchivarComunicacionesDirectas2(_response);
      });
  }

  protected processArchivarComunicacionesDirectas2(
    response: AxiosResponse,
  ): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  archivarComunicacionesDirectasPorUsuario(
    x_api_version?: string | undefined,
    body?: ArchivarComunicacionesDirectasPorUsuarioCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirectaPSP/ArchivarComunicacionesDirectasPorUsuario';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processArchivarComunicacionesDirectasPorUsuario(_response);
      });
  }

  protected processArchivarComunicacionesDirectasPorUsuario(
    response: AxiosResponse,
  ): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerOrganosJudicialesDisponiblesParaComunicacion(
    request?: ObtenerPlazasDisponiblesParaComunicacionQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<ObtenerPlazasDisponiblesResponse> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirectaPSP/ObtenerOrganosJudicialesDisponiblesParaComunicacion?';
    if (request === null)
      throw new globalThis.Error("The parameter 'request' cannot be null.");
    else if (request !== undefined)
      url_ += 'request=' + encodeURIComponent('' + request) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerOrganosJudicialesDisponiblesParaComunicacion(
          _response,
        );
      });
  }

  protected processObtenerOrganosJudicialesDisponiblesParaComunicacion(
    response: AxiosResponse,
  ): Promise<ObtenerPlazasDisponiblesResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ObtenerPlazasDisponiblesResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ObtenerPlazasDisponiblesResponse>(null as any);
  }

  /**
   * @param activas (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerConversacionesPorUsuario2(
    activas?: boolean | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<ConversacionesPorUsuarioResponse> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirectaPSP/ObtenerConversacionesPorUsuario?';
    if (activas === null)
      throw new globalThis.Error("The parameter 'activas' cannot be null.");
    else if (activas !== undefined)
      url_ += 'Activas=' + encodeURIComponent('' + activas) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerConversacionesPorUsuario2(_response);
      });
  }

  protected processObtenerConversacionesPorUsuario2(
    response: AxiosResponse,
  ): Promise<ConversacionesPorUsuarioResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<ConversacionesPorUsuarioResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<ConversacionesPorUsuarioResponse>(null as any);
  }

  /**
   * @param idConversacionEncriptado (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerMensajesPorConversacion2(
    idConversacionEncriptado?: string | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<MensajesPorConversacionResponse> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirectaPSP/ObtenerMensajesPorConversacion?';
    if (idConversacionEncriptado === null)
      throw new globalThis.Error(
        "The parameter 'idConversacionEncriptado' cannot be null.",
      );
    else if (idConversacionEncriptado !== undefined)
      url_ +=
        'IdConversacionEncriptado=' +
        encodeURIComponent('' + idConversacionEncriptado) +
        '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerMensajesPorConversacion2(_response);
      });
  }

  protected processObtenerMensajesPorConversacion2(
    response: AxiosResponse,
  ): Promise<MensajesPorConversacionResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<MensajesPorConversacionResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<MensajesPorConversacionResponse>(null as any);
  }

  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerConversacionesConMensajesNuevos2(
    request?: ObtenerConversacionesConMensajesNuevosQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<string[]> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirectaPSP/ObtenerConversacionesConMensajesNuevos?';
    if (request === null)
      throw new globalThis.Error("The parameter 'request' cannot be null.");
    else if (request !== undefined)
      url_ += 'request=' + encodeURIComponent('' + request) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerConversacionesConMensajesNuevos2(_response);
      });
  }

  protected processObtenerConversacionesConMensajesNuevos2(
    response: AxiosResponse,
  ): Promise<string[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<string[]>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<string[]>(null as any);
  }

  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  obtenerArchivadasConMensajesNuevos2(
    request?: ObtenerArchivadasConMensajesNuevosQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<number> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirectaPSP/ObtenerArchivadasConMensajesNuevos?';
    if (request === null)
      throw new globalThis.Error("The parameter 'request' cannot be null.");
    else if (request !== undefined)
      url_ += 'request=' + encodeURIComponent('' + request) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processObtenerArchivadasConMensajesNuevos2(_response);
      });
  }

  protected processObtenerArchivadasConMensajesNuevos2(
    response: AxiosResponse,
  ): Promise<number> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<number>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<number>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  marcarMensajesLeidos2(
    x_api_version?: string | undefined,
    body?: MarcarMensajesLeidosCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ =
      this.baseUrl + '/api/ComunicacionDirectaPSP/MarcarMensajesLeidos';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processMarcarMensajesLeidos2(_response);
      });
  }

  protected processMarcarMensajesLeidos2(
    response: AxiosResponse,
  ): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @param request (optional)
   * @param x_api_version (optional)
   * @return OK
   */
  comprobarComunicacionesActivadas(
    request?: ComprobarComunicacionesActivadasQuery | undefined,
    x_api_version?: string | undefined,
    signal?: AbortSignal,
  ): Promise<boolean> {
    let url_ =
      this.baseUrl +
      '/api/ComunicacionDirectaPSP/ComprobarComunicacionesActivadas?';
    if (request === null)
      throw new globalThis.Error("The parameter 'request' cannot be null.");
    else if (request !== undefined)
      url_ += 'request=' + encodeURIComponent('' + request) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: AxiosRequestConfig = {
      method: 'GET',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        Accept: 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processComprobarComunicacionesActivadas(_response);
      });
  }

  protected processComprobarComunicacionesActivadas(
    response: AxiosResponse,
  ): Promise<boolean> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = JSON.parse(resultData200);
      return Promise.resolve<boolean>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<boolean>(null as any);
  }

  /**
   * @param x_api_version (optional)
   * @param body (optional)
   * @return Created
   */
  asignarArchivoAMensaje2(
    x_api_version?: string | undefined,
    body?: AsignarArchivoAMensajeCommand | undefined,
    signal?: AbortSignal,
  ): Promise<void> {
    let url_ =
      this.baseUrl + '/api/ComunicacionDirectaPSP/AsignarArchivoAMensaje';
    url_ = url_.replace(/[?&]$/, '');

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: 'POST',
      url: url_,
      headers: {
        'x-api-version':
          x_api_version !== undefined && x_api_version !== null
            ? '' + x_api_version
            : '',
        'Content-Type': 'application/json',
      },
      signal,
    };

    return this.instance
      .request(options_)
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.processAsignarArchivoAMensaje2(_response);
      });
  }

  protected processAsignarArchivoAMensaje2(
    response: AxiosResponse,
  ): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === 'object') {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        'An unexpected server error occurred.',
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }
}

export interface ActualizarConsentimientoComunicacionesCommand {
  consentimiento?: boolean;
}

export interface ArchivarComunicacionesDirectasPorUsuarioCommand {
  idsUsuariosEncriptados?: string[] | undefined;
}

export interface ArchivarConversacionesCommand {
  idsComunicacionesEncriptados?: string[] | undefined;
}

export interface AsignarArchivoAMensajeCommand {
  idComunicacionEncriptado?: string | undefined;
  idArchivo?: string | undefined;
  idMensaje?: string | undefined;
}

export interface ComprobarComunicacionesActivadasQuery {}

export interface ComprobarConsentimientoComunicacionesQuery {}

export interface Conversacion {
  idConversacionEncriptado?: string | undefined;
  titulo?: string | undefined;
  nombreParticipante?: string | undefined;
  ultimoMensaje?: string | undefined;
  fechaUltimoMensaje?: Date;
  estadoUltimoMensaje?: number;
  tipoUltimoMensaje?: number;
  esPropioMensaje?: boolean;
  mensajesSinLeer?: number;
}

export interface ConversacionesPorUsuarioResponse {
  conversaciones?: Conversacion[] | undefined;
}

export interface CrearComunicacionDirectaConElMagistradoCommand {
  idOrganoJudicial?: number;
  titulo?: string | undefined;
  contenidoMensaje?: string | undefined;
  idArchivoEncriptado?: string | undefined;
}

export interface EnviarMensajeCommand {
  idComunicacionEncriptado?: string | undefined;
  contenidoMensaje?: string | undefined;
}

export interface MarcarMensajesLeidosCommand {
  idsMensajesLeidosEncriptados?: string[] | undefined;
}

export interface Mensaje {
  tipoMensaje?: number;
  texto?: string | undefined;
  localizadorArchivo?: string | undefined;
  fechaEnvio?: Date;
  esPropioMensaje?: boolean;
  idMensajeEncriptado?: string | undefined;
  estadoMensaje?: number;
}

export interface MensajesPorConversacionResponse {
  idConversacionEncriptado?: string | undefined;
  idEstadoConversacion?: number;
  usuarioRemitente?: string | undefined;
  mensajes?: Mensaje[] | undefined;
}

export interface ObtenerArchivadasConMensajesNuevosQuery {}

export interface ObtenerConversacionesConMensajesNuevosQuery {}

export interface ObtenerPlazasDisponiblesParaComunicacionQuery {}

export interface ObtenerPlazasDisponiblesResponse {
  organosJudiciales?: OrganoJudicial[] | undefined;
}

export interface OrganoJudicial {
  idOrganoJudicial?: number;
  descripcionOrganoJudicial?: string | undefined;
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any,
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  if (result !== null && result !== undefined) throw result;
  else throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
  return obj && obj.isAxiosError === true;
}
